### ISSUE TITLE
Register json structure must be updated

### ISSUE THREAD

**Issue by hputzek** [martinberlin/udpx#1]
Register json structure must be updated like described in the docs. I'll create a PR for that.

**Comment by hputzek** [comment]
https://github.com/martinberlin/udpx/pull/2

Please refer to docs in gitlab, structure is documented there also in the 3-add-greensock-to-the-party-2 branch

**Comment by martinberlin** [comment]
I guess this is already done. Hendrik Let's open a new Issue if we need to update this again now that https://github.com/IoTPanic/pixelpusher API comes to place.
