### ISSUE TITLE
Receive Reset stripe [99,0,0] / Reset WiFi credentials [114,0,0] short UDP command

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/udpx#14]
Add this to the udp.onPacket switch.
The switch is already analyzing first two bytes. Just for security in case there is a Brotli compressed package starting with 99,0 let's make an extra check for 3rd byte before.
This is already implemented in @IoTPanic pixels in this class method:

New Method added in PIXELS library
```c
void PIXELS::all_off(){
    for(unsigned i = 0; i<PIXELCOUNT; i++){
        #ifdef RGBW
        strip.SetPixelColor(i, RgbwColor(0,0,0,0));
        #else
        strip.SetPixelColor(i, RgbColor(0,0,0));
        #endif
    }
    strip.Show();
}
```

The Android app counterpart for this feature is [udpx-app Issue 10](https://github.com/martinberlin/udpx-app/issues/10)

**Comment by martinberlin** [comment]
Implemented and pull request for new PIXELS.all_off() method send to https://github.com/IoTPanic/pixels/pull/6/files

Waiting for @IoTPanic merge to close this

**Comment by IoTPanic** [comment]
Um, if you send a 0 pixel long pixel packet is is coded to reset the strip for you already. Does that not work?

**Comment by martinberlin** [comment]
Ah I didn't see that in the library. I actually want to make it shorter like this since I want to add at least 2 commands and have them standardized so I can implement them the same way in the Android App.
Actually I would like to have a method in your library that I can call and will turn all off.
