### ISSUE TITLE
Show connection status with the color of first Neopixel

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/udpx#15]
The plan is to show 3 different statuses:

1. BLUE       Waiting for Bluetooth config 
2. GREEN    Connected successfully, got IP
3. RED          Connection failed, will turn to 1.Waiting for config after 4 fails

Let's make this unobtrusive, lighting the pixel only for a second and then going back to all black.

```c
        pix.write(0, 0, 50, 0); // green
        pix.show();
        delay(1000);
        pix.write(0, 0, 1, 0); // green dim
        pix.show();
```

**Comment by IoTPanic** [comment]
Hm, I dont like the user interaction between this and the way BLE setup is initialized. I think I have a solution, do this for now, if I do my solution I will post back in the next two days and you can review and see which you like better.

**Comment by martinberlin** [comment]
Sure just shoot. 
Check how is going first: https://github.com/martinberlin/udpx/compare/feature/14-15-show-status?expand=1
I just want to give a clear indicator since users reported the usability to setup WiFi still needs work. And adding some visual indicator will help at least to know if you got your device online or not. Also added two short commands per UDP: 
[c,0,0] will turn off all pixels (In case you make smaller your output)
[r,0,0] will reset WiFi credentials so we can finally remove that loop that you wanted to remove. 

Anyways it would be nice to have some yellow blinking or just yellow that is "Awaiting configuration, Bluetooth is open"

**Comment by martinberlin** [comment]
Implemented, tested and merged, leave it open for some days just to see your take Samuel

**Comment by martinberlin** [comment]
@IoTPanic Added also a way to reset:
https://github.com/martinberlin/udpx/blob/master/src/main.cpp#L212

App counterpart:
https://github.com/martinberlin/udpx-app/issues/10

seding the command 'r' per UDP. So this waiting loop you mentioned does not need to be there anymore. Now I find it much better.
